<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>GabLuchi</AssemblyName>
    <StartupObject>GabLuchi.Program</StartupObject>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWPF>True</UseWPF>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Version>1.3.9</Version>
    <AssemblyVersion>1.3.9.0</AssemblyVersion>
    <FileVersion>1.3.9.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>GabLuchi\app.manifest</ApplicationManifest>
    <RootNamespace />
    <GabLuchiRuntimeDir>$(LOCALAPPDATA)\GabLuchi\current</GabLuchiRuntimeDir>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="icon.ico" />
    <Resource Include="icon.ico" />
    <None Remove="Assets\gabluchi_logo.png" />
    <Resource Include="Assets\gabluchi_logo.png" />
    <None Update="GabLuchi.config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Extensions.Hosting.Abstractions">
      <HintPath>$(GabLuchiRuntimeDir)\Microsoft.Extensions.Hosting.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
      <HintPath>$(GabLuchiRuntimeDir)\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Wpf.Ui">
      <HintPath>$(GabLuchiRuntimeDir)\Wpf.Ui.dll</HintPath>
    </Reference>
    <Reference Include="VirtualizingWrapPanel">
      <HintPath>$(GabLuchiRuntimeDir)\VirtualizingWrapPanel.dll</HintPath>
    </Reference>
    <Reference Include="CommunityToolkit.Mvvm">
      <HintPath>$(GabLuchiRuntimeDir)\CommunityToolkit.Mvvm.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>$(GabLuchiRuntimeDir)\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Velopack">
      <HintPath>$(GabLuchiRuntimeDir)\Velopack.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Hosting">
      <HintPath>$(GabLuchiRuntimeDir)\Microsoft.Extensions.Hosting.dll</HintPath>
    </Reference>
    <Reference Include="Markdig.Wpf">
      <HintPath>$(GabLuchiRuntimeDir)\Markdig.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Debug">
      <HintPath>$(GabLuchiRuntimeDir)\Microsoft.Extensions.Logging.Debug.dll</HintPath>
    </Reference>
    <Reference Include="System.Diagnostics.DiagnosticSource">
      <HintPath>$(GabLuchiRuntimeDir)\System.Diagnostics.DiagnosticSource.dll</HintPath>
    </Reference>
    <Reference Include="System.Diagnostics.EventLog">
      <HintPath>$(GabLuchiRuntimeDir)\System.Diagnostics.EventLog.dll</HintPath>
    </Reference>
    <Reference Include="System.Security.Cryptography.ProtectedData">
      <HintPath>$(GabLuchiRuntimeDir)\System.Security.Cryptography.ProtectedData.dll</HintPath>
    </Reference>
    <Reference Include="System.Text.Encodings.Web">
      <HintPath>$(GabLuchiRuntimeDir)\System.Text.Encodings.Web.dll</HintPath>
    </Reference>
    <Reference Include="System.Text.Json">
      <HintPath>$(GabLuchiRuntimeDir)\System.Text.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="third_party\goldberg\regular\x64\steam_api64.dll">
      <Link>goldberg\regular\x64\steam_api64.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="third_party\goldberg\regular\x86\steam_api.dll">
      <Link>goldberg\regular\x86\steam_api.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="third_party\goldberg\tools\generate_interfaces_x64.exe">
      <Link>goldberg\tools\generate_interfaces_x64.exe</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="third_party\goldberg\tools\generate_interfaces_x86.exe">
      <Link>goldberg\tools\generate_interfaces_x86.exe</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="third_party\steam_api_bypass\SteamAPICheckBypass.dll">
      <Link>steam_api_bypass\SteamAPICheckBypass.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="third_party\steam_api_bypass\SteamAPICheckBypass_x32.dll">
      <Link>steam_api_bypass\SteamAPICheckBypass_x32.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="third_party\DepotDownloaderMod\DepotDownloaderMod.dll" Condition="Exists('third_party\DepotDownloaderMod\DepotDownloaderMod.dll')">
      <Link>DepotDownloaderMod\DepotDownloaderMod.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="third_party\7za\7za.exe">
      <Link>7za.exe</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="third_party\7za\7z.dll" Condition="Exists('third_party\7za\7z.dll')">
      <Link>7z.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="third_party\dlc_unlockers\smokeapi\smoke_api32.dll" Condition="Exists('third_party\dlc_unlockers\smokeapi\smoke_api32.dll')">
      <Link>dlc_unlockers\smokeapi\smoke_api32.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="third_party\dlc_unlockers\smokeapi\smoke_api64.dll" Condition="Exists('third_party\dlc_unlockers\smokeapi\smoke_api64.dll')">
      <Link>dlc_unlockers\smokeapi\smoke_api64.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="third_party\dlc_unlockers\creamapi\steam_api.dll" Condition="Exists('third_party\dlc_unlockers\creamapi\steam_api.dll')">
      <Link>dlc_unlockers\creamapi\steam_api.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="third_party\dlc_unlockers\creamapi\steam_api64.dll" Condition="Exists('third_party\dlc_unlockers\creamapi\steam_api64.dll')">
      <Link>dlc_unlockers\creamapi\steam_api64.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="third_party\dlc_unlockers\uplayr1\uplay_r1_loader.dll" Condition="Exists('third_party\dlc_unlockers\uplayr1\uplay_r1_loader.dll')">
      <Link>dlc_unlockers\uplayr1\uplay_r1_loader.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="third_party\dlc_unlockers\uplayr1\uplay_r1_loader64.dll" Condition="Exists('third_party\dlc_unlockers\uplayr1\uplay_r1_loader64.dll')">
      <Link>dlc_unlockers\uplayr1\uplay_r1_loader64.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="third_party\dlc_unlockers\uplayr2\upc_r2_loader.dll" Condition="Exists('third_party\dlc_unlockers\uplayr2\upc_r2_loader.dll')">
      <Link>dlc_unlockers\uplayr2\upc_r2_loader.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="third_party\dlc_unlockers\uplayr2\upc_r2_loader64.dll" Condition="Exists('third_party\dlc_unlockers\uplayr2\upc_r2_loader64.dll')">
      <Link>dlc_unlockers\uplayr2\upc_r2_loader64.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>